# Generated by Django 4.1.3 on 2023-01-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="describes_failure",
            field=models.BooleanField(
                help_text="Whether the article describes a failure. This field is set by a human or the classifier.",
                null=True,
                verbose_name="Describes Failure",
            ),
        ),
    ]
