# Generated by Django 4.1.3 on 2023-01-05 17:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_article_describes_failure"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="describes_failure_confidence",
            field=models.FloatField(
                editable=False,
                help_text="Confidence of the classifier in whether the article describes a failure.",
                null=True,
                verbose_name="Describes Failure Confidence",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="embedding",
            field=models.FileField(
                editable=False,
                help_text="NumPy array of the embedding of the article stored as a file.",
                null=True,
                upload_to="embeddings",
                verbose_name="Embedding",
            ),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="sources",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(max_length=255),
                blank=True,
                help_text="Sources to search for news articles, such as nytimes.com,wired.com.",
                null=True,
                size=None,
                verbose_name="Sources",
            ),
        ),
    ]
