# Generated by Django 4.1.3 on 2023-04-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_article_describes_failure_confidence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="failure",
            name="behavior",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="description",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="dimension",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="display",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="ended_at",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="location",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="manual_annotation",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="name",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="semantics",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="started_at",
        ),
        migrations.AddField(
            model_name="failure",
            name="NSEcauses",
            field=models.TextField(
                blank=True, null=True, verbose_name="Non-Software Causes"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="SEcauses",
            field=models.TextField(
                blank=True, null=True, verbose_name="Software Causes"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="application_option",
            field=models.CharField(
                blank=True,
                choices=[("true", "true"), ("false", "false"), ("-1", "unknown")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="application_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Application Rationale"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="behaviour_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "crash"),
                    ("1", "omission"),
                    ("2", "timing"),
                    ("3", "value"),
                    ("4", "Byzantine fault"),
                    ("-1", "unknown"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="behaviour_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Behaviour Rationale"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="boundary_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "within the system"),
                    ("1", "outside the system"),
                    ("2", "both"),
                    ("3", "neither"),
                    ("-1", "unknown"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="boundary_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Boundary Rationale"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="capability_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "accidental"),
                    ("1", "development incompetence"),
                    ("2", "both"),
                    ("3", "neither"),
                    ("-1", "unknown"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="capability_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Capability Rationale"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="communication_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("false", "False"),
                    ("1", "link level"),
                    ("2", "connectivity level"),
                    ("-1", "unknown"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="communication_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Communication Rationale"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="cps_option",
            field=models.CharField(
                blank=True,
                choices=[("true", "true"), ("false", "false"), ("-1", "unknown")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="cps_rationale",
            field=models.TextField(blank=True, null=True, verbose_name="CPS Rationale"),
        ),
        migrations.AddField(
            model_name="failure",
            name="dimension_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "hardware"),
                    ("1", "software"),
                    ("2", "both"),
                    ("3", "neither"),
                    ("-1", "unknown"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="dimension_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Dimension Rationale"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="domain_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "automotive"),
                    ("1", "critical infrastructure"),
                    ("2", "healthcare"),
                    ("3", "energy"),
                    ("4", "transportation"),
                    ("5", "infrastructure"),
                    ("6", "aerospace"),
                    ("7", "telecommunications"),
                    ("-1", "unknown"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="domain_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Domain Rationale"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="duration_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "permanent"),
                    ("1", "temporary"),
                    ("2", "intermittent"),
                    ("-1", "unknown"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="duration_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Duration Rationale"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="impacts",
            field=models.TextField(blank=True, null=True, verbose_name="Impacts"),
        ),
        migrations.AddField(
            model_name="failure",
            name="intent_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "deliberate"),
                    ("1", "accidental"),
                    ("2", "both"),
                    ("3", "neither"),
                    ("-1", "unknown"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="intent_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Intent Rationale"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="mitigations",
            field=models.TextField(blank=True, null=True, verbose_name="Mitigations"),
        ),
        migrations.AddField(
            model_name="failure",
            name="nature_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "human actions"),
                    ("1", "non human actions"),
                    ("2", "both"),
                    ("3", "neither"),
                    ("-1", "unknown"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="nature_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nature Rationale"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="objective_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "malicious"),
                    ("1", "non-malicious"),
                    ("2", "both"),
                    ("3", "neither"),
                    ("-1", "unknown"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="objective_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Objective Rationale"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="perception_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "sensors"),
                    ("1", "actuators"),
                    ("2", "processing unit"),
                    ("3", "network communication"),
                    ("4", "embedded software"),
                    ("-1", "unknown"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="perception_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Perception Rationale"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="phase_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "system design"),
                    ("1", "operation"),
                    ("2", "both"),
                    ("3", "neither"),
                    ("-1", "unknown"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="phase_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Phase Rationale"
            ),
        ),
        migrations.AddField(
            model_name="failure",
            name="summary",
            field=models.TextField(blank=True, null=True, verbose_name="Summary"),
        ),
        migrations.AddField(
            model_name="failure",
            name="system",
            field=models.TextField(blank=True, null=True, verbose_name="System"),
        ),
        migrations.AddField(
            model_name="failure",
            name="time",
            field=models.TextField(blank=True, null=True, verbose_name="Time"),
        ),
        migrations.AddField(
            model_name="failure",
            name="title",
            field=models.TextField(blank=True, null=True, verbose_name="Title"),
        ),
    ]
