# Generated by Django 4.1.3 on 2023-04-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_remove_failure_behavior_remove_failure_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="failure",
            name="published",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the article was published.",
                null=True,
                verbose_name="Published",
            ),
        ),
    ]
