# Generated by Django 4.1.3 on 2023-04-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_alter_failure_application_option_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="failures",
        ),
        migrations.AddField(
            model_name="failure",
            name="failure",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.article",
            ),
        ),
        migrations.DeleteModel(
            name="FailureCause",
        ),
    ]
