# Generated by Django 4.1.3 on 2023-04-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_remove_article_failures_failure_failure_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="failure",
            name="NSEcauses",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="SEcauses",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="application_option",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="application_rationale",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="behaviour_option",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="behaviour_rationale",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="boundary_option",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="boundary_rationale",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="capability_option",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="capability_rationale",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="communication_option",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="communication_rationale",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="cps_option",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="cps_rationale",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="dimension_option",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="dimension_rationale",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="domain_option",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="domain_rationale",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="duration_option",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="duration_rationale",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="impacts",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="intent_option",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="intent_rationale",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="mitigations",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="nature_option",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="nature_rationale",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="objective_option",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="objective_rationale",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="perception_option",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="perception_rationale",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="phase_option",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="phase_rationale",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="system",
        ),
        migrations.RemoveField(
            model_name="failure",
            name="time",
        ),
        migrations.AddField(
            model_name="article",
            name="NSEcauses",
            field=models.TextField(
                blank=True, null=True, verbose_name="Non-Software Causes"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="SEcauses",
            field=models.TextField(
                blank=True, null=True, verbose_name="Software Causes"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="application_option",
            field=models.TextField(
                blank=True, null=True, verbose_name="Application Option"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="application_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Application Rationale"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="behaviour_option",
            field=models.TextField(
                blank=True, null=True, verbose_name="Behaviour Option"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="behaviour_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Behaviour Rationale"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="boundary_option",
            field=models.TextField(
                blank=True, null=True, verbose_name="Boundary Option"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="boundary_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Boundary Rationale"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="capability_option",
            field=models.TextField(
                blank=True, null=True, verbose_name="Capability Option"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="capability_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Capability Rationale"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="communication_option",
            field=models.TextField(
                blank=True, null=True, verbose_name="Communication Option"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="communication_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Communication Rationale"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="cps_option",
            field=models.TextField(blank=True, null=True, verbose_name="CPS Option"),
        ),
        migrations.AddField(
            model_name="article",
            name="cps_rationale",
            field=models.TextField(blank=True, null=True, verbose_name="CPS Rationale"),
        ),
        migrations.AddField(
            model_name="article",
            name="dimension_option",
            field=models.TextField(
                blank=True, null=True, verbose_name="Dimension Option"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="dimension_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Dimension Rationale"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="domain_option",
            field=models.TextField(blank=True, null=True, verbose_name="Domain Option"),
        ),
        migrations.AddField(
            model_name="article",
            name="domain_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Domain Rationale"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="duration_option",
            field=models.TextField(
                blank=True, null=True, verbose_name="Duration Option"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="duration_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Duration Rationale"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="impacts",
            field=models.TextField(blank=True, null=True, verbose_name="Impacts"),
        ),
        migrations.AddField(
            model_name="article",
            name="intent_option",
            field=models.TextField(blank=True, null=True, verbose_name="Intent Option"),
        ),
        migrations.AddField(
            model_name="article",
            name="intent_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Intent Rationale"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="mitigations",
            field=models.TextField(blank=True, null=True, verbose_name="Mitigations"),
        ),
        migrations.AddField(
            model_name="article",
            name="nature_option",
            field=models.TextField(blank=True, null=True, verbose_name="Nature Option"),
        ),
        migrations.AddField(
            model_name="article",
            name="nature_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nature Rationale"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="objective_option",
            field=models.TextField(
                blank=True, null=True, verbose_name="Objective Option"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="objective_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Objective Rationale"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="perception_option",
            field=models.TextField(
                blank=True, null=True, verbose_name="Perception Option"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="perception_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Perception Rationale"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="phase_option",
            field=models.TextField(blank=True, null=True, verbose_name="Phase Option"),
        ),
        migrations.AddField(
            model_name="article",
            name="phase_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Phase Rationale"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="system",
            field=models.TextField(blank=True, null=True, verbose_name="System"),
        ),
        migrations.AddField(
            model_name="article",
            name="time",
            field=models.TextField(blank=True, null=True, verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=models.TextField(blank=True, null=True, verbose_name="Summary"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.TextField(blank=True, null=True, verbose_name="Title"),
        ),
    ]
