# Generated by Django 4.1.3 on 2023-04-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_remove_failure_nsecauses_remove_failure_secauses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchquery",
            name="end_month",
            field=models.IntegerField(
                blank=True,
                help_text="News articles will be searched until this month. This field is optional.",
                null=True,
                verbose_name="End Month",
            ),
        ),
        migrations.AddField(
            model_name="searchquery",
            name="start_month",
            field=models.IntegerField(
                blank=True,
                help_text="News articles will be searched from this month onwards. This field is optional.",
                null=True,
                verbose_name="Start Month",
            ),
        ),
    ]
