# Generated by Django 4.1.3 on 2023-04-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0011_article_headline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="describes_failure",
        ),
        migrations.AddField(
            model_name="article",
            name="describes_failure_ChatGPT",
            field=models.BooleanField(
                help_text="Whether the article describes a failure. This field is set by ChatGPT.",
                null=True,
                verbose_name="Describes Failure",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="describes_failure_os",
            field=models.BooleanField(
                help_text="Whether the article describes a failure. This field is set by an open-source classifier.",
                null=True,
                verbose_name="Describes Failure",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="summary_init",
            field=models.TextField(
                blank=True,
                help_text="Summary of article to run through classifier to check if article describes a software failure.",
                null=True,
                verbose_name="Classifier Summary",
            ),
        ),
    ]
