# Generated by Django 4.1.3 on 2023-04-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0012_remove_article_describes_failure_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="describes_failure_ChatGPT",
            new_name="describes_failure",
        ),
        migrations.RemoveField(
            model_name="article",
            name="describes_failure_confidence",
        ),
        migrations.RemoveField(
            model_name="article",
            name="describes_failure_os",
        ),
    ]
