# Generated by Django 4.1.3 on 2023-04-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0013_rename_describes_failure_chatgpt_article_describes_failure_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="NSEcauses_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Non-Software Causes Embedding"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="SEcauses_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Software Causes Embedding"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="impacts_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Impacts Embedding"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="mitigations_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mitigations Embedding"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="summary_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Summary Embedding"
            ),
        ),
    ]
