# Generated by Django 4.1.3 on 2023-04-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0014_article_nsecauses_embedding_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="summary_init",
        ),
        migrations.AddField(
            model_name="article",
            name="article_summary",
            field=models.TextField(
                blank=True,
                help_text="Summary of the article generated by an OS summarizer model.",
                verbose_name="article_summary",
            ),
        ),
    ]
