# Generated by Django 4.1.3 on 2023-04-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0015_remove_article_summary_init_article_article_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="organization",
            field=models.TextField(blank=True, null=True, verbose_name="Organization"),
        ),
    ]
