# Generated by Django 4.1.3 on 2023-04-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0016_article_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the earliest article was published.",
                        null=True,
                        verbose_name="Published",
                    ),
                ),
                (
                    "title",
                    models.TextField(blank=True, null=True, verbose_name="Title"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="Summary"),
                ),
            ],
            options={
                "verbose_name": "Failure",
                "verbose_name_plural": "Failures",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="similarity_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Cosine similarity score"
            ),
        ),
        migrations.DeleteModel(
            name="Failure",
        ),
        migrations.AddField(
            model_name="article",
            name="incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="articles.incident",
            ),
        ),
    ]
