# Generated by Django 4.1.3 on 2023-05-03 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0017_incident_article_similarity_score_delete_failure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="articles.incident",
            ),
        ),
    ]
