# Generated by Django 4.1.3 on 2023-05-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0019_alter_incident_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incident",
            options={"verbose_name": "Incident", "verbose_name_plural": "Incidents"},
        ),
        migrations.AddField(
            model_name="article",
            name="organization_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Organization Embedding"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="system_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="System Embedding"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="time_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Time Embedding"
            ),
        ),
    ]
