# Generated by Django 4.1.3 on 2023-09-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0020_alter_incident_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="article",
            name="organization_embedding",
        ),
        migrations.AddField(
            model_name="article",
            name="ImpactedOrg",
            field=models.TextField(blank=True, null=True, verbose_name="ImpactedOrg"),
        ),
        migrations.AddField(
            model_name="article",
            name="ImpactedOrg_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="ImpactedOrg Embedding"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="ResponsibleOrg",
            field=models.TextField(
                blank=True, null=True, verbose_name="ResponsibleOrg"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="ResponsibleOrg_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="ResponsibleOrg Embedding"
            ),
        ),
    ]
