# Generated by Django 4.1.3 on 2023-09-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0021_remove_article_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="analyzable_failure",
            field=models.BooleanField(
                help_text="Whether the article can be used to conduct a failure analysis. This field is set by ChatGPT.",
                null=True,
                verbose_name="Analyzable Failure",
            ),
        ),
    ]
