# Generated by Django 4.1.3 on 2023-10-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0024_remove_incident_incident_stored_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="ImpactedOrg_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="ImpactedOrg Embedding"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="NSEcauses_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Non-Software Causes Embedding"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="ResponsibleOrg_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="ResponsibleOrg Embedding"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="SEcauses_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Software Causes Embedding"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="impacts_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Impacts Embedding"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="mitigations_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Mitigations Embedding"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="summary_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Summary Embedding"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="system_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="System Embedding"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="time_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Time Embedding"
            ),
        ),
    ]
