# Generated by Django 4.1.3 on 2023-10-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0025_incident_impactedorg_embedding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="scrape_successful",
            field=models.BooleanField(
                help_text="Whether the article was scraped successfully.",
                null=True,
                verbose_name="Scrape Successful",
            ),
        ),
    ]
