# Generated by Django 4.1.3 on 2023-10-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0026_article_scrape_successful"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="sources",
            field=models.TextField(blank=True, null=True, verbose_name="Sources"),
        ),
        migrations.AddField(
            model_name="incident",
            name="sources",
            field=models.TextField(blank=True, null=True, verbose_name="Sources"),
        ),
    ]
