# Generated by Django 4.1.3 on 2024-01-30 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0028_remove_article_sources_remove_incident_sources_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident_Ko",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "published",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the earliest article was published.",
                        null=True,
                        verbose_name="Published",
                    ),
                ),
                (
                    "title",
                    models.TextField(blank=True, null=True, verbose_name="Title"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="Summary"),
                ),
                (
                    "system",
                    models.TextField(blank=True, null=True, verbose_name="System"),
                ),
                ("time", models.TextField(blank=True, null=True, verbose_name="Time")),
                (
                    "SEcauses",
                    models.TextField(
                        blank=True, null=True, verbose_name="Software Causes"
                    ),
                ),
                (
                    "NSEcauses",
                    models.TextField(
                        blank=True, null=True, verbose_name="Non-Software Causes"
                    ),
                ),
                (
                    "impacts",
                    models.TextField(blank=True, null=True, verbose_name="Impacts"),
                ),
                (
                    "mitigations",
                    models.TextField(blank=True, null=True, verbose_name="Mitigations"),
                ),
                (
                    "ResponsibleOrg",
                    models.TextField(
                        blank=True, null=True, verbose_name="ResponsibleOrg"
                    ),
                ),
                (
                    "ImpactedOrg",
                    models.TextField(blank=True, null=True, verbose_name="ImpactedOrg"),
                ),
                (
                    "references",
                    models.TextField(blank=True, null=True, verbose_name="References"),
                ),
                (
                    "phase_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Phase Option"
                    ),
                ),
                (
                    "boundary_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Boundary Option"
                    ),
                ),
                (
                    "nature_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nature Option"
                    ),
                ),
                (
                    "dimension_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dimension Option"
                    ),
                ),
                (
                    "objective_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Objective Option"
                    ),
                ),
                (
                    "intent_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Intent Option"
                    ),
                ),
                (
                    "capability_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Capability Option"
                    ),
                ),
                (
                    "duration_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Duration Option"
                    ),
                ),
                (
                    "domain_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Domain Option"
                    ),
                ),
                (
                    "cps_option",
                    models.TextField(blank=True, null=True, verbose_name="CPS Option"),
                ),
                (
                    "perception_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Perception Option"
                    ),
                ),
                (
                    "communication_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Communication Option"
                    ),
                ),
                (
                    "application_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Application Option"
                    ),
                ),
                (
                    "behaviour_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Behaviour Option"
                    ),
                ),
                (
                    "phase_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Phase Rationale"
                    ),
                ),
                (
                    "boundary_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Boundary Rationale"
                    ),
                ),
                (
                    "nature_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nature Rationale"
                    ),
                ),
                (
                    "dimension_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dimension Rationale"
                    ),
                ),
                (
                    "objective_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Objective Rationale"
                    ),
                ),
                (
                    "intent_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Intent Rationale"
                    ),
                ),
                (
                    "capability_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Capability Rationale"
                    ),
                ),
                (
                    "duration_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Duration Rationale"
                    ),
                ),
                (
                    "domain_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Domain Rationale"
                    ),
                ),
                (
                    "cps_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="CPS Rationale"
                    ),
                ),
                (
                    "perception_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Perception Rationale"
                    ),
                ),
                (
                    "communication_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Communication Rationale"
                    ),
                ),
                (
                    "application_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Application Rationale"
                    ),
                ),
                (
                    "behaviour_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Behaviour Rationale"
                    ),
                ),
                (
                    "summary_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="Summary Embedding"
                    ),
                ),
                (
                    "time_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="Time Embedding"
                    ),
                ),
                (
                    "system_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="System Embedding"
                    ),
                ),
                (
                    "ResponsibleOrg_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="ResponsibleOrg Embedding"
                    ),
                ),
                (
                    "ImpactedOrg_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="ImpactedOrg Embedding"
                    ),
                ),
                (
                    "SEcauses_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="Software Causes Embedding"
                    ),
                ),
                (
                    "NSEcauses_embedding",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Non-Software Causes Embedding",
                    ),
                ),
                (
                    "impacts_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="Impacts Embedding"
                    ),
                ),
                (
                    "mitigations_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mitigations Embedding"
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident_Ko",
                "verbose_name_plural": "Incidents_Ko",
            },
        ),
        migrations.CreateModel(
            name="Article_Ko",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL of the article.",
                        max_length=510,
                        unique=True,
                        verbose_name="URL",
                    ),
                ),
                (
                    "published",
                    models.DateTimeField(
                        help_text="Date and time when the article was published.",
                        verbose_name="Published",
                    ),
                ),
                (
                    "source",
                    models.URLField(
                        help_text="URL of the source of the article, such as nytimes.com.",
                        verbose_name="Source",
                    ),
                ),
                (
                    "article_summary",
                    models.TextField(
                        blank=True,
                        help_text="Summary of the article generated by an OS summarizer model.",
                        verbose_name="article_summary",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Body of the article scraped from the URL.",
                        verbose_name="Body",
                    ),
                ),
                (
                    "embedding",
                    models.FileField(
                        editable=False,
                        help_text="NumPy array of the embedding of the article stored as a file.",
                        null=True,
                        upload_to="embeddings",
                        verbose_name="Embedding",
                    ),
                ),
                (
                    "scraped_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the article was scraped.",
                        verbose_name="Scraped at",
                    ),
                ),
                (
                    "scrape_successful",
                    models.BooleanField(
                        help_text="Whether the article was scraped successfully.",
                        null=True,
                        verbose_name="Scrape Successful",
                    ),
                ),
                (
                    "describes_failure",
                    models.BooleanField(
                        help_text="Whether the article describes a failure. This field is set by ChatGPT.",
                        null=True,
                        verbose_name="Describes Failure",
                    ),
                ),
                (
                    "analyzable_failure",
                    models.BooleanField(
                        help_text="Whether the article can be used to conduct a failure analysis. This field is set by ChatGPT.",
                        null=True,
                        verbose_name="Analyzable Failure",
                    ),
                ),
                (
                    "article_stored",
                    models.BooleanField(
                        help_text="Whether the article has been stored into the vector database.",
                        null=True,
                        verbose_name="Article_Ko Stored",
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Cosine similarity score"
                    ),
                ),
                (
                    "headline",
                    models.TextField(blank=True, null=True, verbose_name="Headline"),
                ),
                (
                    "title",
                    models.TextField(blank=True, null=True, verbose_name="Title"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="Summary"),
                ),
                (
                    "system",
                    models.TextField(blank=True, null=True, verbose_name="System"),
                ),
                ("time", models.TextField(blank=True, null=True, verbose_name="Time")),
                (
                    "SEcauses",
                    models.TextField(
                        blank=True, null=True, verbose_name="Software Causes"
                    ),
                ),
                (
                    "NSEcauses",
                    models.TextField(
                        blank=True, null=True, verbose_name="Non-Software Causes"
                    ),
                ),
                (
                    "impacts",
                    models.TextField(blank=True, null=True, verbose_name="Impacts"),
                ),
                (
                    "mitigations",
                    models.TextField(blank=True, null=True, verbose_name="Mitigations"),
                ),
                (
                    "ResponsibleOrg",
                    models.TextField(
                        blank=True, null=True, verbose_name="ResponsibleOrg"
                    ),
                ),
                (
                    "ImpactedOrg",
                    models.TextField(blank=True, null=True, verbose_name="ImpactedOrg"),
                ),
                (
                    "references",
                    models.TextField(blank=True, null=True, verbose_name="References"),
                ),
                (
                    "phase_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Phase Option"
                    ),
                ),
                (
                    "boundary_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Boundary Option"
                    ),
                ),
                (
                    "nature_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nature Option"
                    ),
                ),
                (
                    "dimension_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dimension Option"
                    ),
                ),
                (
                    "objective_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Objective Option"
                    ),
                ),
                (
                    "intent_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Intent Option"
                    ),
                ),
                (
                    "capability_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Capability Option"
                    ),
                ),
                (
                    "duration_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Duration Option"
                    ),
                ),
                (
                    "domain_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Domain Option"
                    ),
                ),
                (
                    "cps_option",
                    models.TextField(blank=True, null=True, verbose_name="CPS Option"),
                ),
                (
                    "perception_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Perception Option"
                    ),
                ),
                (
                    "communication_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Communication Option"
                    ),
                ),
                (
                    "application_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Application Option"
                    ),
                ),
                (
                    "behaviour_option",
                    models.TextField(
                        blank=True, null=True, verbose_name="Behaviour Option"
                    ),
                ),
                (
                    "phase_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Phase Rationale"
                    ),
                ),
                (
                    "boundary_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Boundary Rationale"
                    ),
                ),
                (
                    "nature_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Nature Rationale"
                    ),
                ),
                (
                    "dimension_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Dimension Rationale"
                    ),
                ),
                (
                    "objective_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Objective Rationale"
                    ),
                ),
                (
                    "intent_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Intent Rationale"
                    ),
                ),
                (
                    "capability_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Capability Rationale"
                    ),
                ),
                (
                    "duration_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Duration Rationale"
                    ),
                ),
                (
                    "domain_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Domain Rationale"
                    ),
                ),
                (
                    "cps_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="CPS Rationale"
                    ),
                ),
                (
                    "perception_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Perception Rationale"
                    ),
                ),
                (
                    "communication_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Communication Rationale"
                    ),
                ),
                (
                    "application_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Application Rationale"
                    ),
                ),
                (
                    "behaviour_rationale",
                    models.TextField(
                        blank=True, null=True, verbose_name="Behaviour Rationale"
                    ),
                ),
                (
                    "summary_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="Summary Embedding"
                    ),
                ),
                (
                    "time_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="Time Embedding"
                    ),
                ),
                (
                    "system_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="System Embedding"
                    ),
                ),
                (
                    "ResponsibleOrg_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="ResponsibleOrg Embedding"
                    ),
                ),
                (
                    "ImpactedOrg_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="ImpactedOrg Embedding"
                    ),
                ),
                (
                    "SEcauses_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="Software Causes Embedding"
                    ),
                ),
                (
                    "NSEcauses_embedding",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Non-Software Causes Embedding",
                    ),
                ),
                (
                    "impacts_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="Impacts Embedding"
                    ),
                ),
                (
                    "mitigations_embedding",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mitigations Embedding"
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="articles.incident_ko",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article_Ko",
                "verbose_name_plural": "Articles_Ko",
            },
        ),
    ]
