# Generated by Django 4.1.3 on 2023-12-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0028_remove_article_sources_remove_incident_sources_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(
                help_text="URL of the article.",
                max_length=2048,
                unique=True,
                verbose_name="URL",
            ),
        ),
    ]
