# Generated by Django 4.1.3 on 2024-01-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0029_incident_ko_article_ko"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article_ko",
            name="url",
        ),
    ]
