# Generated by Django 4.1.3 on 2024-01-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0030_remove_article_ko_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="article_ko",
            name="relevant_to_story",
            field=models.BooleanField(
                help_text="Whether the article is relevant to the ko database story.",
                null=True,
                verbose_name="Relevant to story",
            ),
        ),
    ]
