# Generated by Django 4.1.3 on 2024-02-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0029_alter_article_url"),
        ("articles", "0031_article_ko_relevant_to_story"),
    ]

    operations = []
