# Generated by Django 4.1.3 on 2024-02-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0033_incident_fixes_incident_preventions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="mitigations",
        ),
        migrations.RemoveField(
            model_name="article",
            name="mitigations_embedding",
        ),
        migrations.RemoveField(
            model_name="article_ko",
            name="mitigations",
        ),
        migrations.RemoveField(
            model_name="article_ko",
            name="mitigations_embedding",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="mitigations",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="mitigations_embedding",
        ),
        migrations.RemoveField(
            model_name="incident_ko",
            name="mitigations",
        ),
        migrations.RemoveField(
            model_name="incident_ko",
            name="mitigations_embedding",
        ),
    ]
