# Generated by Django 4.1.3 on 2024-02-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0034_remove_article_mitigations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="fixes",
            field=models.TextField(blank=True, null=True, verbose_name="Fixes"),
        ),
        migrations.AddField(
            model_name="article",
            name="fixes_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Fixes Embedding"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="preventions",
            field=models.TextField(blank=True, null=True, verbose_name="Preventions"),
        ),
        migrations.AddField(
            model_name="article",
            name="preventions_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Preventions Embedding"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="fixes_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Fixes Embedding"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="preventions_embedding",
            field=models.TextField(
                blank=True, null=True, verbose_name="Preventions Embedding"
            ),
        ),
    ]
