# Generated by Django 4.1.3 on 2024-03-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0035_article_fixes_article_fixes_embedding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article_ko",
            name="articleID",
            field=models.IntegerField(
                blank=True,
                help_text="Article ID of the Ko article",
                null=True,
                verbose_name="article id",
            ),
        ),
        migrations.AddField(
            model_name="article_ko",
            name="storyID",
            field=models.IntegerField(
                blank=True,
                help_text="Story ID of the Ko article",
                null=True,
                verbose_name="story id",
            ),
        ),
    ]
