# Generated by Django 4.1.3 on 2024-03-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0036_article_tokens_incident_complete_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="consequence_option",
            field=models.TextField(blank=True, null=True, verbose_name="Domain Option"),
        ),
        migrations.AddField(
            model_name="incident",
            name="consequence_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Domain Rationale"
            ),
        ),
    ]
