# Generated by Django 4.1.3 on 2024-03-27 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0036_article_ko_articleid_article_ko_storyid"),
        ("articles", "0038_article_experiment"),
    ]

    operations = []
