# Generated by Django 4.1.3 on 2024-04-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0039_merge_20240327_1941"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="rag",
            field=models.BooleanField(
                help_text="Whether RAG was used to create a failure report for the incident.",
                null=True,
                verbose_name="RAG",
            ),
        ),
    ]
