# Generated by Django 4.1.3 on 2024-04-22 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0040_codebook_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="parent_theme",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent theme of this sub-theme.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_themes",
                to="articles.theme",
                verbose_name="Parent Theme",
            ),
        ),
    ]
