# Generated by Django 4.1.3 on 2024-04-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0042_subtheme_remove_theme_codebook_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtheme",
            name="definition",
            field=models.TextField(
                default="no_val",
                help_text="The definition of the theme.",
                verbose_name="Definition",
            ),
        ),
        migrations.AlterField(
            model_name="subtheme",
            name="incidents",
            field=models.ManyToManyField(
                blank=True,
                related_name="subthemes",
                to="articles.incident",
                verbose_name="Incidents",
            ),
        ),
        migrations.AlterField(
            model_name="subtheme",
            name="postmortem_key",
            field=models.CharField(
                default="no_val",
                help_text="The postmortem of which the theme belongs.",
                max_length=100,
                verbose_name="Postmortem Key",
            ),
        ),
        migrations.AlterField(
            model_name="subtheme",
            name="sub_theme",
            field=models.CharField(
                default="no_val",
                help_text="The sub theme name.",
                max_length=100,
                verbose_name="Sub theme",
            ),
        ),
    ]
