# Generated by Django 4.1.3 on 2024-05-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0040_incident_rag"),
        (
            "articles",
            "0043_alter_subtheme_definition_alter_subtheme_incidents_and_more",
        ),
    ]

    operations = []
