# Generated by Django 4.1.3 on 2024-05-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0044_merge_20240520_0534"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="consequence_option",
            field=models.TextField(
                blank=True, null=True, verbose_name="Consequence Option"
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="consequence_rationale",
            field=models.TextField(
                blank=True, null=True, verbose_name="Consequence Rationale"
            ),
        ),
    ]
